image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2

stages:
  - build
  - deploy

build_image:
  stage: build
  script:
    - docker build -t desafio-dio .

run_container:
  stage: deploy
  script:
    - docker rm -f desafio-dio || true
    - docker run -d --name desafio-dio -p 80:80 desafio-dio
